import { chromium } from 'playwright';
import ffmpeg from 'ffmpeg-static';
import { mkdir, mkdtemp, writeFile, copyFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { resolve, join } from 'node:path';
import { spawn } from 'node:child_process';
const base = process.env.SITE_URL || 'http://127.0.0.1:4337';
const media = resolve('public/media');
await mkdir(media, { recursive: true });
const temp = await mkdtemp(join(tmpdir(), 'rig-os-tour-'));
const browser = await chromium.launch({headless:true});
const context = await browser.newContext({ viewport:{width:1600,height:1000}, colorScheme:'dark', deviceScaleFactor:1, recordVideo:{dir:temp,size:{width:1600,height:1000}} });
const page = await context.newPage();
const errors=[];
page.on('pageerror',error=>errors.push(error.message));
const cues=[];
const started=Date.now();
const seconds=()=>((Date.now()-started)/1000);
async function hold(text, duration=3500) { const start=seconds(); await page.waitForTimeout(duration); cues.push({start,end:seconds(),text}); console.log(`Scene ${cues.length} recorded`); }
try {
  await page.goto(base, {waitUntil:'networkidle'});
  await page.screenshot({path:join(media,'tour-poster.png')});
  await copyFile(join(media,'tour-poster.png'), join(media,'site-preview.png'));
  await hold('Rig OS is a local computer-use runtime. This is a tour of its public architecture and documentation.',4500);
  await page.locator('[data-node="runtime"]').click();
  await hold('Models propose actions. You review them. The runtime checks permission and current state before input.',4200);
  await page.getByRole('link',{name:'Explore the system map',exact:true}).click();
  await page.locator('#nodes .node').first().waitFor();
  await page.screenshot({path:join(media,'map-poster.png')});
  await hold('The system map connects 120 responsibilities. Each box leads to its explanation and source.',4000);
  await page.getByRole('button',{name:/Plan and review desktop work/}).click();
  await hold('Choose a journey to follow one workflow through the system, in order.',3300);
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await hold('Step through the handoffs. See which component owns each decision.',3000);
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.locator('#nodes .active-step').click();
  await hold('Descriptions include the boundaries and limits of each responsibility.',2800);
  await page.locator('#component-sources .source-button').first().click();
  await page.locator('#source-dialog').waitFor({state:'visible'});
  await hold('Open the exact source snapshot with the cited line highlighted.',4200);
  await page.locator('#source-dialog [data-close-dialog]').click();
  await page.getByRole('button',{name:'Source file index',exact:true}).click();
  await page.getByLabel('Filter paths',{exact:true}).fill('runtime/policy');
  await hold('Search source paths when you already know where you want to look.',3200);
  await page.locator('#files-dialog [data-close-dialog]').click();
  await page.getByRole('link',{name:'Documentation ↗',exact:true}).click();
  await hold('The documentation library publishes all 51 Markdown documents from the repository.',3400);
  await page.getByRole('button',{name:/Search docs/}).click();
  await page.locator('#doc-query').pressSequentially('providers',{delay:100});
  await page.locator('#search-results a').first().waitFor();
  await hold('Search the full text. Read setup, architecture, operating guides, and recorded evidence.',4000);
  await page.locator('#search-results a').first().click();
  await hold('Read the document, copy commands, or go back to the original source.',3500);
  await page.goto(base+'/docs/docs/open-source/VERIFICATION/',{waitUntil:'networkidle'});
  await hold('Keep the limits visible. Recorded results have a scope, and failed gates stay in the documentation.',3800);
  await page.goto(base+'/#explore',{waitUntil:'networkidle'});
  await hold('Explore at rig-os.netlify.app. Built by Brad Clonan, open to Software Architect, Staff / Principal Engineer, and applied AI roles.',4500);
} finally {
  const recording=page.video();
  await context.close();
  await recording.saveAs(join(temp,'tour.webm'));
  await browser.close();
}
const stamp=(s,sep='.')=>{const ms=Math.floor(s*1000);return `${String(Math.floor(ms/3600000)).padStart(2,'0')}:${String(Math.floor(ms/60000)%60).padStart(2,'0')}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}${sep}${String(ms%1000).padStart(3,'0')}`;};
const vtt='WEBVTT\n\n'+cues.map((c,i)=>`${i+1}\n${stamp(c.start)} --> ${stamp(c.end)}\n${c.text}\n`).join('\n');
const srt=cues.map((c,i)=>`${i+1}\n${stamp(c.start,',')} --> ${stamp(c.end,',')}\n${c.text}\n`).join('\n');
await writeFile(join(media,'rig-os-tour.vtt'),vtt);
await writeFile(join(temp,'captions.srt'),srt);
await writeFile(join(media,'rig-os-tour-transcript.txt'),'Inside Rig OS. Recorded walkthrough of the real static documentation website. No runtime or native desktop execution occurs in this clip. Silent video with explanatory captions.\n\n'+cues.map(c=>c.text).join('\n\n')+'\n');
function run(args){return new Promise((resolve,reject)=>{const child=spawn(ffmpeg,args,{cwd:temp,windowsHide:true,stdio:['ignore','ignore','pipe']});let err='';child.stderr.on('data',x=>err+=x);child.on('error',reject);child.on('close',code=>code===0?resolve():reject(new Error(err)));});}
await run(['-y','-i','tour.webm','-an','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',join(media,'rig-os-tour.mp4')]);
await run(['-y','-i','tour.webm','-vf',"pad=1600:1120:0:0:color=0x0b1517,subtitles=captions.srt:force_style='FontName=Segoe UI,FontSize=10,PrimaryColour=&H00E9EEE8,OutlineColour=&H0017150B,BorderStyle=1,Outline=1,Shadow=0,MarginV=8,Alignment=2'",'-an','-c:v','libx264','-preset','medium','-crf','20','-pix_fmt','yuv420p','-movflags','+faststart',join(media,'rig-os-social.mp4')]);
await writeFile(join(media,'tour-recording.json'),JSON.stringify({recordedAt:new Date().toISOString(),url:base,level:'Real static website and map interactions. No local runtime or native desktop execution.',errors,cues,viewport:{width:1600,height:1000},video:'rig-os-tour.mp4',socialVideo:'rig-os-social.mp4'},null,2));
if(errors.length)throw new Error(errors.join('\n'));
console.log(JSON.stringify({status:'PASS',seconds:seconds(),media,captions:cues.length}));
